name: ShellCheck CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run ShellCheck
        run: shellcheck scripts/*.sh scripts/lib/*.sh scripts/host-prep/*.sh
